### ISSUE TITLE
Sign In Errors

### ISSUE THREAD

**Issue by jematson** [d-maltos/CS372Project#3]
If you try to log in with a password that does not meet requirements, it will pop up with the password requirements, but if you then type in a password that meet requirements but is still incorrect, the error that pops up is still the password requirements, not incorrect password. Incorrect attempts are also not increased.

**Comment by Trevonator8** [comment]
Issue fixed, removed accidental commenting in code, form messages can be changed properly now

**Comment by jematson** [comment]
Tested again and sign in errors are now correct. Issue resolved.
